import type { PositionedElementConfig } from '../services/PositionedElementsService';

// Группировка комнат по коридорам с разделением на категории
export const corridorGroups = {
  corridor1: {
    name: "Коридор 1",
    rooms: [
      {
        id: 'Room1',
        number: 1,
        x: 2046,
        y: 3014,
        width: 198,
        height: 160,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 1
      },
      {
        id: 'Room2',
        number: 2,
        x: 1696,
        y: 3014,
        width: 346,
        height: 160,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 1
      },
      {
        id: 'Room3',
        number: 3,
        x: 1486,
        y: 3014,
        width: 200,
        height: 160,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 1
      },
      {
        id: 'Room4',
        number: 4,
        x: 1258,
        y: 3014,
        width: 224,
        height: 160,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 1
      },
      {
        id: 'Room5',
        number: 5,
        x: 1165,
        y: 3014,
        width: 78,
        height: 164,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        category: 'stairs',
        zIndex: 1,
        visible: true,
        corridor: 1
      },
      {
        id: 'Room6',
        number: 6,
        x: 1482,
        y: 2744,
        width: 138,
        height: 160,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 1
      }, 
      {
        id: 'Room7',
        number: 7,
        x: 1258,
        y: 2744,
        width: 210,
        height: 158,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 1
      },
      {
        id: 'Room8',
        number: 8,
        x: 1166,
        y: 2744,
        width: 78,
        height: 158,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        category: 'toilet',
        zIndex: 1,
        visible: true,
        corridor: 1
      },
      
      ]
  },
  corridor2: {
    name: "Коридор 2",
    rooms: [
      // Комнаты коридора 2 (только уникальные)
      {
        id: 'Room10',
        number: 10,
        x: 2778,
        y: 2316,
        width: 156,
        height: 132,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 2
      },
      {
        id: 'Room11',
        number: 11,
        x: 2778,
        y: 2112,
        width: 156,
        height: 200,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 2
      },
      {
        id: 'Room12',
        number: 12,
        x: 2778,
        y: 1826,
        width: 156,
        height: 274,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 2
      },
      {
        id: 'Room13',
        number: 13,
        x: 2778,
        y: 1614,
        width: 156,
        height: 206,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 2
      },
      {
        id: 'Room14',
        number: 14,
        x: 2626,
        y: 1388,
        width: 306,
        height: 212,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 2
      },
      {
        id: 'Room19',
        number: 19,
        x: 2778,
        y: 1388,
        width: 306,
        height: 212,
        rotation: 0,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 2
      }
      ]
  },
  corridor3: {
    name: "Коридор 3",
    rooms: [
      // Комнаты коридора 2 (только уникальные)
      {
        id: 'Room20',
        number: 20,
        x: 642,
        y: 2922,
        width: 116,
        height: 80,
        rotation: -17,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 3
      },
      {
        id: 'Room21',
        number: 21,
        x: 597,
        y: 2685,
        width: 114,
        height: 238,
        rotation: -17,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 3
      },
      {
        id: 'Room22',
        number: 22,
        x: 535,
        y: 2518,
        width: 116,
        height: 172,
        rotation: -17,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 3
      },
      {
        id: 'Room23',
        number: 23,
        x: 482,
        y: 2341,
        width: 116,
        height: 178,
        rotation: -17,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 3
      },
      {
        id: 'Room24',
        number: 24,
        x: 446,
        y: 2282,
        width: 116,
        height: 50,
        rotation: -17,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 3
      },
      {
         id: 'Room25',
         number: 25,
         x: 822,
         y: 2872,
         width: 109,
         height: 76,
         rotation: -17,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 3
      },
      {
         id: 'Room26',
         number: 26,
         x: 800,
         y: 2808,
         width: 109,
         height: 64,
         rotation: -17,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 3
      },
      {
         id: 'Room27',
         number: 27,
         x: 762,
         y: 2618,
         width: 109,
         height: 194,
         rotation: -17,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 3
      },
      {
         id: 'Room28',
         number: 28,
         x: 720,
         y: 2526,
         width: 110,
         height: 94,
         rotation: -17,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 3
      },
      {
         id: 'Room29',
         number: 29,
         x: 696,
         y: 2466,
         width: 110,
         height: 60,
         rotation: -17,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 3
      }
       
      ]
  },
  corridor4: {
    name: "Коридор 4",
    rooms: [
      // Комнаты коридора 4 (только уникальные)
      {
         id: 'Room30',
         number: 30,
         x: 352,
         y: 2008,
         width: 160,
         height: 56,
         rotation: 0,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 4
      },
      {
          id: 'Room31',
          number: 31,
          x: 354,
          y: 1840,
          width: 160,
          height: 154,
          rotation: 1,
          color: '#BFF355',
          borderColor: '#A8D444',
          borderWidth: 2,
          borderRadius: 8,
          fontSize: 24,
          fontColor: '#ffffff',
          zIndex: 1,
          visible: true,
          corridor: 4
      },
      {
           id: 'Room32',
           number: 32,
           x: 357,
           y: 1674,
           width: 158,
           height: 152,
           rotation: 1,
           color: '#BFF355',
           borderColor: '#A8D444',
           borderWidth: 2,
           borderRadius: 8,
           fontSize: 24,
           fontColor: '#ffffff',
           zIndex: 1,
           visible: true,
           corridor: 4
      },
      {
            id: 'Room33',
            number: 33,
            x: 357,
            y: 1596,
            width: 161,
            height: 64,
            rotation: 0.80,
            color: '#BFF355',
            borderColor: '#A8D444',
            borderWidth: 2,
            borderRadius: 8,
            fontSize: 24,
            fontColor: '#ffffff',
            zIndex: 1,
            visible: true,
            corridor: 4
      },
      {
             id: 'Room34',
             number: 34,
             x: 360,
             y: 1465,
             width: 161,
             height: 78,
             rotation: 0.80,
             color: '#BFF355',
             borderColor: '#A8D444',
             borderWidth: 2,
             borderRadius: 8,
             fontSize: 24,
             fontColor: '#ffffff',
             zIndex: 1,
             visible: true,
             corridor: 4
      },
      {
              id: 'Room35',
              number: 35,
              x: 361,
              y: 1308,
              width: 161,
              height: 145,
              rotation: 0.80,
              color: '#BFF355',
              borderColor: '#A8D444',
              borderWidth: 2,
              borderRadius: 8,
              fontSize: 24,
              fontColor: '#ffffff',
              zIndex: 1,
              visible: true,
              corridor: 4
      },
      {
               id: 'Room36',
               number: 36,
               x: 364,
               y: 1146,
               width: 160,
               height: 148,
               rotation: 0.80,
               color: '#BFF355',
               borderColor: '#A8D444',
               borderWidth: 2,
               borderRadius: 8,
               fontSize: 24,
               fontColor: '#ffffff',
               zIndex: 1,
               visible: true,
               corridor: 4
      },
      {
                id: 'Room37',
                number: 37,
                x: 280,
                y: 1074,
                width: 244,
                height: 62,
                rotation: 0.80,
                color: '#BFF355',
                borderColor: '#A8D444',
                borderWidth: 2,
                borderRadius: 8,
                fontSize: 24,
                fontColor: '#ffffff',
                zIndex: 1,
                visible: true,
                corridor: 4
      },
      {
                 id: 'Room38',
                 number: 38,
                 x: 280,
                 y: 962,
                 width: 246,
                 height: 94,
                 rotation: 0.80,
                 color: '#BFF355',
                 borderColor: '#A8D444',
                 borderWidth: 2,
                 borderRadius: 8,
                 fontSize: 24,
                 fontColor: '#ffffff',
                 zIndex: 1,
                 visible: true,
                 corridor: 4
      },
      {
                   id: 'Room39',
                   number: 39,
                   x: 594,
                   y: 1940,
                   width: 160,
                   height: 122,
                   rotation: 0.80,
                   color: '#BFF355',
                   borderColor: '#A8D444',
                   borderWidth: 2,
                   borderRadius: 8,
                   fontSize: 24,
                   fontColor: '#ffffff',
                   zIndex: 1,
                   visible: true,
                   corridor: 4
      },
      {
                     id: 'Room40',
                     number: 40,
                     x: 596,
                     y: 1772,
                     width: 160,
                     height: 160,
                     rotation: 0.80,
                     color: '#BFF355',
                     borderColor: '#A8D444',
                     borderWidth: 2,
                     borderRadius: 8,
                     fontSize: 24,
                     fontColor: '#ffffff',
                     zIndex: 1,
                     visible: true,
                     corridor: 4
      },
      {
                       id: 'Room41',
                       number: 41,
                       x: 596,
                       y: 1615,
                       width: 162,
                       height: 154,
                       rotation: 0.80,
                       color: '#BFF355',
                       borderColor: '#A8D444',
                       borderWidth: 2,
                       borderRadius: 8,
                       fontSize: 24,
                       fontColor: '#ffffff',
                       zIndex: 1,
                       visible: true,
                       corridor: 4
      },
      {
                         id: 'Room42',
                         number: 42,
                         x: 604,
                         y: 1191,
                         width: 160,
                         height: 157,
                         rotation: 0.80,
                         color: '#BFF355',
                         borderColor: '#A8D444',
                         borderWidth: 2,
                         borderRadius: 8,
                         fontSize: 24,
                         fontColor: '#ffffff',
                         zIndex: 1,
                         visible: true,
                         corridor: 4
      },
      {
                           id: 'Room43',
                           number: 43,
                           x: 606,
                           y: 1078,
                           width: 160,
                           height: 110,
                           rotation: 0.80,
                           color: '#BFF355',
                       borderColor: '#A8D444',
                           borderWidth: 2,
                           borderRadius: 8,
                           fontSize: 24,
                           fontColor: '#ffffff',
                           zIndex: 1,
                           visible: true,
                           corridor: 4
      }


      ]
  },
  corridor5: {
    name: "Коридор 5",
    rooms: [
      // Комнаты коридора 2 (только уникальные)
      {
         id: 'Room50',
         number: 50,
         x: 772,
         y: 856,
         width: 124,
         height: 190,
         rotation: 0.70,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 5
      },
      {
        id: 'Room51',
        number: 51,
        x: 676,
        y: 470,
        width: 90,
        height: 200,
        rotation: 0.70,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 5
      },
      {
        id: 'Room52',
        number: 52,
        x: 676,
        y: 369,
        width: 92,
        height: 94,
        rotation: 0.70,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 5
      },
      {
        id: 'Room53',
        number: 53,
        x: 678,
        y: 210,
        width: 92,
        height: 152,
        rotation: 0.70,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 5
      },
      {
        id: 'Room54',
        number: 54,
        x: 680,
        y: 52,
        width: 92,
        height: 154,
        rotation: 0.70,
        color: '#BFF355',
        borderColor: '#A8D444',
        borderWidth: 2,
        borderRadius: 8,
        fontSize: 24,
        fontColor: '#ffffff',
        zIndex: 1,
        visible: true,
        corridor: 5
      },
      {
         id: 'Room55',
         number: 55,
         x: 512,
         y: 766,
         width: 89,
         height: 62,
         rotation: 0.70,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 5
      },
      {
         id: 'Room56',
         number: 56,
         x: 514,
         y: 614,
         width: 88,
         height: 140,
         rotation: 0.70,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 5
      },
      {
         id: 'Room57',
         number: 57,
         x: 514,
         y: 544,
         width: 88,
         height: 62,
         rotation: 0.70,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 5
      },
      {
         id: 'Room58',
         number: 58,
         x: 516,
         y: 380,
         width: 88,
         height: 154,
         rotation: 0.70,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 5
      },
      {
         id: 'Room59',
         number: 59,
         x: 516,
         y: 304,
         width: 88,
         height: 66,
         rotation: 0.70,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 5
      },
      {
         id: 'Room60',
         number: 60,
         x: 516,
         y: 226,
         width: 90,
         height: 68,
         rotation: 0.70,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 5
      },
      {
         id: 'Room61',
         number: 61,
         x: 482,
         y: 50,
         width: 126,
         height: 124,
         rotation: 0.70,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 5
      },
      {
         id: 'Room62',
         number: 62,
         x: 368,
         y: 50,
         width: 108,
         height: 124,
         rotation: 0.70,
         color: '#BFF355',
         borderColor: '#A8D444',
         borderWidth: 2,
         borderRadius: 8,
         fontSize: 24,
         fontColor: '#ffffff',
         zIndex: 1,
         visible: true,
         corridor: 5
      }    
      ]
  },
};

// Плоский массив для рендерера (обратная совместимость)
export const squaresConfig: PositionedElementConfig[] = Object.values(corridorGroups)
  .flatMap(corridor => corridor.rooms);

export default squaresConfig;
